<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>homectl</AssemblyName>
    <RootNamespace>Home.Cli</RootNamespace>
    <PublishAot Condition="'$(RuntimeIdentifier)' != ''">true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Home.Client/Home.Client.csproj" />
  </ItemGroup>
</Project>
